In [1]:
# If save the whole model

from keras.models import load_model
model= load_model('FFNN_iris.model')

In [2]:
import numpy as np

test_data=[4.5,3.0,1.2,0.1]
test_data=np.array(test_data)
print(test_data)

[4.5 3.  1.2 0.1]


In [3]:
#1D to 2D 

test_data=test_data.reshape(1,-1)
print(test_data)

[[4.5 3.  1.2 0.1]]


In [4]:
print(test_data.shape)

(1, 4)


In [6]:
result=model.predict(test_data)
print(result)

[[1. 0. 0.]]


In [7]:
label=np.argmax(result,axis=1)
print(label)

[0]


0 means setosa