In [1]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
#an empty NN created

model.add(Dense(64,input_dim=4,activation='relu')) #first hidden layer
model.add(Dense(128,activation='relu'))  #2nd hidden layer
model.add(Dense(64,activation='relu'))  #3rd hidden layer
model.add(Dense(3,activation='softmax')) #output layer

#because of classification problem, we have to use categorical crossentropy 
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 195       
Total params: 17,091
Trainable params: 17,091
Non-trainable params: 0
_________________________________________________________________


In [2]:
model.load_weights('FFNN_iris_weights.h5')

In [3]:
import numpy as np

test_data=[4.5,3.0,1.2,0.1]
test_data=np.array(test_data)
print(test_data)
test_data=test_data.reshape(1,-1)
print(test_data)
print(test_data.shape)

[4.5 3.  1.2 0.1]
[[4.5 3.  1.2 0.1]]
(1, 4)


In [4]:
result=model.predict(test_data)
print(result)

[[1. 0. 0.]]
